#!/usr/bin/env python3
"""
本文件功能：
- 从已有 ms-swift/Qwen2.5-Omni JSONL 中读取视频路径，批量抽取音频，并生成带 `audios` 字段的新 JSONL。

主要内容：
- 解析输入 JSONL。
- 调用 ffmpeg 从视频中导出 wav 音频。
- 把抽取得到的音频路径写回新 JSONL，同时保留原 `videos`、`messages` 和 `meta`。

使用方式：
- `python scripts/extract_audio_and_build_av_jsonl.py --input_jsonl ... --output_jsonl ... --audio_root ...`
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence


def setup_logging() -> None:
    """初始化统一日志格式。"""
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    """
    函数功能：
    - 解析音频抽取与 JSONL 增强脚本参数。
    """
    parser = argparse.ArgumentParser(
        description="Extract audio tracks from videos and write a new JSONL with audios fields."
    )
    parser.add_argument("--input_jsonl", required=True, help="Source JSONL generated by prepare_swift_av_sft.py.")
    parser.add_argument("--output_jsonl", required=True, help="New JSONL path with audios field.")
    parser.add_argument(
        "--audio_root",
        required=True,
        help="Directory to store extracted audio files. Relative layout follows the input video paths.",
    )
    parser.add_argument("--audio_ext", default=".wav", help="Extracted audio extension, default .wav.")
    parser.add_argument("--sample_rate", type=int, default=16000, help="Target audio sample rate.")
    parser.add_argument("--audio_channels", type=int, default=1, help="Target audio channels.")
    parser.add_argument("--ffmpeg", default="ffmpeg", help="ffmpeg executable path.")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing extracted audio files.")
    parser.add_argument("--dry_run", action="store_true", help="Only plan output paths without running ffmpeg.")
    return parser.parse_args(argv)


def load_jsonl(path: Path) -> List[Dict[str, Any]]:
    """读取 JSONL 文件。"""
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            if not line.strip():
                continue
            row = json.loads(line)
            row["_line_number"] = line_number
            rows.append(row)
    return rows


def normalize_video_path(video_path: str, jsonl_path: Path) -> Path:
    """把 JSONL 中的相对或绝对视频路径转成绝对路径。"""
    path = Path(video_path).expanduser()
    if path.is_absolute():
        return path.resolve(strict=False)
    return (jsonl_path.parent / path).resolve(strict=False)


def output_audio_path(video_path: Path, audio_root: Path, suffix: str) -> Path:
    """
    函数功能：
    - 为单个视频生成稳定的输出音频路径。

    关键逻辑：
    - 为避免不同目录下同名文件冲突，优先保留视频路径的目录层级。
    """
    drive = video_path.drive.rstrip(":").replace("\\", "/")
    relative_parts = [part for part in video_path.parts[1:-1] if part not in {"/", "\\"}]
    target_dir = audio_root / drive / Path(*relative_parts) if drive else audio_root / Path(*relative_parts)
    return target_dir / f"{video_path.stem}{suffix}"


def extract_audio(
    ffmpeg: str,
    video_path: Path,
    audio_path: Path,
    sample_rate: int,
    audio_channels: int,
    overwrite: bool,
) -> None:
    """
    函数功能：
    - 调用 ffmpeg 从视频中抽取音频为 wav 等格式。
    """
    audio_path.parent.mkdir(parents=True, exist_ok=True)
    command = [
        ffmpeg,
        "-y" if overwrite else "-n",
        "-i",
        str(video_path),
        "-vn",
        "-acodec",
        "pcm_s16le",
        "-ar",
        str(sample_rate),
        "-ac",
        str(audio_channels),
        str(audio_path),
    ]
    completed = subprocess.run(command, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    if completed.returncode != 0:
        raise RuntimeError(
            f"ffmpeg failed for {video_path} -> {audio_path}: {completed.stderr.strip() or completed.stdout.strip()}"
        )


def iter_augmented_rows(rows: Iterable[Dict[str, Any]], args: argparse.Namespace, input_jsonl: Path) -> List[Dict[str, Any]]:
    """
    函数功能：
    - 对 JSONL 逐行补齐 `audios` 字段，并按需执行音频抽取。
    """
    audio_root = Path(args.audio_root).expanduser()
    augmented: List[Dict[str, Any]] = []
    for row in rows:
        videos = row.get("videos") or []
        if not videos:
            raise ValueError(f"{input_jsonl}:{row.get('_line_number')} has no videos field")
        video_path = normalize_video_path(str(videos[0]), input_jsonl)
        audio_path = output_audio_path(video_path, audio_root, args.audio_ext)
        if not args.dry_run and (args.overwrite or not audio_path.exists()):
            extract_audio(
                ffmpeg=args.ffmpeg,
                video_path=video_path,
                audio_path=audio_path,
                sample_rate=args.sample_rate,
                audio_channels=args.audio_channels,
                overwrite=args.overwrite,
            )
        new_row = {key: value for key, value in row.items() if key != "_line_number"}
        new_row["audios"] = [str(audio_path.resolve(strict=False))]
        augmented.append(new_row)
    return augmented


def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> None:
    """写出 JSONL 文件。"""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False))
            handle.write("\n")


def main(argv: Optional[Sequence[str]] = None) -> int:
    """
    函数功能：
    - 音频抽取与 AV JSONL 增强脚本主流程。
    """
    setup_logging()
    args = parse_args(argv)
    input_jsonl = Path(args.input_jsonl).expanduser()
    output_jsonl = Path(args.output_jsonl).expanduser()
    rows = load_jsonl(input_jsonl)
    logging.info("Loaded %d rows from %s", len(rows), input_jsonl)
    augmented = iter_augmented_rows(rows, args, input_jsonl)
    write_jsonl(output_jsonl, augmented)
    logging.info("Wrote %d rows with audios field to %s", len(augmented), output_jsonl)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
